#!/usr/bin/env bash -o errexit
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd "$ROOT_DIR"


# install
pip install --requirement requirements.txt
pip freeze > requirements-macos.txt.lock
